---

- name: Fix local hostname
  hosts: all
  sudo: True
  tasks:
    - shell: echo "$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) ip-$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4 | sed 's/\./-/g')" >> /etc/hosts
