---

- name: Install / Launch Redis
  hosts: all
  sudo: True
  tasks:
    - action: apt pkg=redis-server state=installed force=yes

    - template: >
        src=../configs/redis.conf
        dest=/etc/redis/redis.conf
        owner=root
        group=root
        mode=644

    - service: name=redis-server state=restarted enabled=yes
